# 数据集路径
train_file_path: /mnt/a782f50b-253f-43da-ac99-945477898740/chensheng/Project1/train/train
val_file_path: /mnt/a782f50b-253f-43da-ac99-945477898740/chensheng/Project1/train/val
test_file_path: /mnt/a782f50b-253f-43da-ac99-945477898740/chensheng/Project1/predict/test
# 文件路径
lve: /home/chensheng/1Project/Project1/FLAME/flame_mask/lve.txt
fdd: /home/chensheng/1Project/Project1/FLAME/flame_mask/fdd.txt
template: /home/chensheng/1Project/Project1/FLAME/mean_template.npy
flame_model: /home/chensheng/1Project/Project1/FLAME/flame_model/generic_model.pkl
static_landmark_embedding: /home/chensheng/1Project/Project1/FLAME/flame_model/flame_static_embedding.pkl
dynamic_landmark_embedding: /home/chensheng/1Project/Project1/FLAME/flame_model/flame_dynamic_embedding.npy

# python VQVAE2/Predict.py
# python Generation/Predict.py
predict:
  # 保存路径 _STtb _tb _STb _b
  vqvae_dir: /home/chensheng/1Project/Project1/VQVAE2/checkpoints_STtb/model_train.pth
  generation_dir: /home/chensheng/1Project/Project1/Generation/checkpoints_STtb/model_train.pth
  save_path: /mnt/a782f50b-253f-43da-ac99-945477898740/chensheng/Project1/predict/STtb_vertices
  # 参数设置
  gpu: 0  #0/1
  # flame参数
  shape: 300  #形状参数数量
  expression: 100  #表情参数数量

# python VQVAE2/Train.py
stage1:
  # 保存路径 _STtb _tb _STb _b
  # STtb (loss:2-1-6-8) 0.29918841753967507(664) 0.4138502219030934(97)
  #MVE: 4.7187e-04
  #LVE: 2.6687e-05
  #FDD: 4.8311e-06
  #MVE: 4.6472e-04
  #LVE: 2.6111e-05
  #FDD: 6.9039e-06

  # tb (loss:2-1-6-8) 0.3127259479628669(789) 0.45128521419340567(154)
  #MVE: 5.3760e-04
  #LVE: 4.1413e-05
  #FDD: 7.3008e-06
  #MVE: 5.0125e-04
  #LVE: 3.5938e-05
  #FDD: 9.8172e-06
  # STb (loss:2-1-6-8) 0.3238215772703351(798) 0.5002147478442038(675)
  #MVE: 5.1768e-04
  #LVE: 3.8321e-05
  #FDD: 4.6525e-06
  #MVE: 5.1526e-04
  #LVE: 3.7877e-05
  #FDD: 4.7169e-06
  # b (loss:2-1-6-8) 0.3511657658427831(798) 0.5216977817396964(215)
  #MVE: 5.8438e-04
  #LVE: 5.4308e-05
  #FDD: 7.8425e-06
  #MVE: 5.6977e-04
  #LVE: 5.1502e-05
  #FDD: 1.3350e-05

  checkpoint_dir: /home/chensheng/1Project/Project1/VQVAE2/checkpoints_STtb
  # 参数设置
  gpu: 0  #0/1
  epochs: 800  #800
  batch_size: 64  #64
  learning_rate: 1  #1
  warmup_steps: 5000  #5000
  # vqvae参数
  embed_dim: 256  #256
  num_heads: 32  #32
  num_layers_top: 4  #4
  num_layers_bottom: 6  #6
  num_layers_decoder: 4  #4
  num_embeddings_top: 64  #64
  num_embeddings_bottom: 256  #256

# python Generation/Train.py
stage2:
  # 保存路径 _STtb _tb _STb _b
  # STtb (loss:0.2-0.1-6-8) 0.41703075616475355(192) 0.7005579901523278(43)
  #MVE: 6.7385e-04
  #LVE: 5.8672e-05
  #FDD: 1.5541e-05
  #MEE: 5.3748e-05
  #CE: 4.8864e-05
  #Diversity: 2.5478e-04
  #MVE: 6.7441e-04
  #LVE: 5.8570e-05
  #FDD: 1.4540e-05
  #MEE: 5.4820e-05
  #CE: 5.0644e-05
  #Diversity: 2.2021e-04

  # tb (loss:0.2-0.1-6-8) 1.015090220729879(165) 1.583611469776904(54)
  #MVE: 1.0305e-03
  #LVE: 1.0600e-04
  #FDD: 8.4650e-05
  #MEE: 1.0009e-04
  #CE: 8.6765e-05
  #Diversity: 3.4116e-04
  #MVE: 1.0968e-03
  #LVE: 1.1577e-04
  #FDD: 6.2692e-05
  #MEE: 1.1131e-04
  #CE: 9.8790e-05
  #Diversity: 2.8169e-04
  # STb (loss:0.2-0.1-6-8) 0.3921820748639673(200) 0.7439439902540113(141)
  #MVE: 7.1180e-04
  #LVE: 6.7076e-05
  #FDD: 2.0216e-05
  #MEE: 6.4304e-05
  #CE: 6.0540e-05
  #Diversity: 1.3151e-04
  #MVE: 7.1095e-04
  #LVE: 6.6867e-05
  #FDD: 1.9117e-05
  #MEE: 6.4224e-05
  #CE: 6.0397e-05
  #Diversity: 1.4186e-04
  # b (loss:0.2-0.1-6-8) 0.5217265719845814(196) 1.3883438892051823(198)
  #MVE: 1.0417e-03
  #LVE: 1.0796e-04
  #FDD: 5.7755e-05
  #MEE: 1.0489e-04
  #CE: 9.7055e-05
  #Diversity: 1.6003e-04
  #MVE: 1.0199e-03
  #LVE: 1.0427e-04
  #FDD: 7.4303e-05
  #MEE: 1.0166e-04
  #CE: 9.4104e-05
  #Diversity: 1.5447e-04

  vqvae_dir: /home/chensheng/1Project/Project1/VQVAE2/checkpoints_STtb/model_train.pth
  checkpoint_dir: /home/chensheng/1Project/Project1/Generation/checkpoints_STtb
  # 参数设置
  gpu: 0  #0/1
  epochs: 200  #200
  batch_size: 16  #16
  learning_rate: 0.1  #0.1
  warmup_steps: 10000  #10000
  # 窗口层参数
  num_heads: 8  #8
  num_layers_top: 6  #6
  num_layers_bottom: 4  #4